### ISSUE TITLE
咱们工程的jar包能按普通方式给吗？用aar这种方式跟另一个依赖有冲突

### ISSUE THREAD

**Issue by houwenhao4147** [anyunzhong/AndroidTimelineView#10]
用aar这种方式的jar包跟另一个依赖有冲突

**Comment by zk0301** [comment]
我的也是。用了这个项目，莫名其妙的cn.bingoogolapple.refreshlayout.BGARefreshLayout就会报错。而且这个项目的下拉刷新操作(在我的项目)会闪退，郁闷了。
